FROM python:3.8.5

RUN pip3 install --upgrade pip 

RUN pip3 install pandas
RUN pip3 install numpy
RUN pip3 install scikit-learn
RUN pip3 install matplotlib
RUN pip3 install seaborn
RUN pip3 install jupyter
RUN pip3 install pyspark
